#!/bin/sh

# Pre-JENV way
#export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
#echo "JAVA_HOME=$JAVA_HOME"

# JENV
eval "$(jenv init -)"
jenv shell 1.8
# jenv means never having to say JAVA_HOME 
# It UNSETS JAVA_HOME, and so, relies on apps to set JAVA_HOME relative to the java executable

java -version
