#!/bin/bash

mkdir -p ./_Archive

D="${HOME}/Library/Application Support/Code/User/"
if [ -e "$D" ]; then
    echo "Installing files in $D"
    cp "$D"/*.json ./_Archive
    cp ./keybindings.json "$D"/
    cp ./settings.json "$D"/
else
    echo "$D does not exist. Not installing files in $D"
fi





